// @generated by scripts/validate-icons.py from assets/icons/source/*.svg.
// Do not edit by hand.

#[rustfmt::skip]
fn icon_geometry(icon: Icon) -> &'static [Primitive] {
    match icon {
        Icon::Activate => &[
            Primitive::Polyline(&[
                (9.0, 5.0),
                (16.0, 12.0),
                (9.0, 19.0),
            ]),
        ],
        Icon::AppMark => &[
            Primitive::Polyline(&[
                (4.0, 18.0),
                (4.0, 6.0),
                (11.0, 6.0),
            ]),
            Primitive::Polyline(&[
                (4.0, 11.0),
                (9.0, 11.0),
            ]),
            Primitive::Polyline(&[
                (13.0, 8.0),
                (16.0, 11.0),
                (13.0, 14.0),
            ]),
            Primitive::Polyline(&[
                (17.5, 16.0),
                (21.0, 16.0),
            ]),
        ],
        Icon::AuthRequired => &[
            Primitive::Circle { x: 8.0, y: 12.0, radius: 4.0 },
            Primitive::Polyline(&[
                (12.0, 12.0),
                (21.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (17.0, 12.0),
                (17.0, 15.0),
            ]),
            Primitive::Polyline(&[
                (20.0, 12.0),
                (20.0, 14.0),
            ]),
        ],
        Icon::Back => &[
            Primitive::Polyline(&[
                (15.0, 5.0),
                (8.0, 12.0),
                (15.0, 19.0),
            ]),
        ],
        Icon::Clear => &[
            Primitive::Polyline(&[
                (4.0, 15.0),
                (12.0, 5.0),
                (20.0, 12.0),
                (14.0, 20.0),
                (8.0, 20.0),
                (4.0, 15.0),
            ]),
            Primitive::Polyline(&[
                (9.0, 11.0),
                (15.0, 16.0),
            ]),
            Primitive::Polyline(&[
                (3.0, 20.0),
                (21.0, 20.0),
            ]),
        ],
        Icon::Close => &[
            Primitive::Polyline(&[
                (6.0, 6.0),
                (18.0, 18.0),
            ]),
            Primitive::Polyline(&[
                (18.0, 6.0),
                (6.0, 18.0),
            ]),
        ],
        Icon::CommandPalette => &[
            Primitive::Rectangle { x: 3.0, y: 4.0, width: 18.0, height: 16.0, radius: 2.0 },
            Primitive::Polyline(&[
                (7.0, 9.0),
                (10.0, 12.0),
                (7.0, 15.0),
            ]),
            Primitive::Polyline(&[
                (12.0, 15.0),
                (17.0, 15.0),
            ]),
        ],
        Icon::Copy => &[
            Primitive::Rectangle { x: 8.0, y: 8.0, width: 11.0, height: 12.0, radius: 2.0 },
            Primitive::Polyline(&[
                (16.0, 8.0),
                (16.0, 6.0),
                (15.8478, 5.2346),
                (15.4142, 4.5858),
                (14.7654, 4.1522),
                (14.0, 4.0),
                (6.0, 4.0),
                (5.2346, 4.1522),
                (4.5858, 4.5858),
                (4.1522, 5.2346),
                (4.0, 6.0),
                (4.0, 16.0),
                (4.1522, 16.7654),
                (4.5858, 17.4142),
                (5.2346, 17.8478),
                (6.0, 18.0),
                (8.0, 18.0),
            ]),
        ],
        Icon::Diagnostics => &[
            Primitive::Polyline(&[
                (3.0, 12.0),
                (7.0, 12.0),
                (9.0, 7.0),
                (13.0, 17.0),
                (15.0, 12.0),
                (21.0, 12.0),
            ]),
            Primitive::Rectangle { x: 3.0, y: 3.0, width: 18.0, height: 18.0, radius: 2.0 },
        ],
        Icon::Disconnect => &[
            Primitive::Polyline(&[
                (9.5, 14.5),
                (7.0, 17.0),
                (5.853, 17.7664),
                (4.5, 18.0355),
                (3.147, 17.7664),
                (2.0, 17.0),
                (1.2336, 15.853),
                (0.9645, 14.5),
                (1.2336, 13.147),
                (2.0, 12.0),
                (5.0, 9.0),
                (5.9977, 8.2955),
                (7.1768, 7.9767),
                (8.3936, 8.0825),
                (9.5, 8.6),
            ]),
            Primitive::Polyline(&[
                (14.5, 9.5),
                (17.0, 7.0),
                (18.147, 6.2336),
                (19.5, 5.9645),
                (20.853, 6.2336),
                (22.0, 7.0),
                (22.7664, 8.147),
                (23.0355, 9.5),
                (22.7664, 10.853),
                (22.0, 12.0),
                (19.0, 15.0),
                (18.0023, 15.7045),
                (16.8232, 16.0233),
                (15.6064, 15.9175),
                (14.5, 15.4),
            ]),
            Primitive::Polyline(&[
                (8.0, 16.0),
                (16.0, 8.0),
            ]),
            Primitive::Polyline(&[
                (4.0, 4.0),
                (20.0, 20.0),
            ]),
        ],
        Icon::Edit => &[
            Primitive::Polyline(&[
                (4.0, 20.0),
                (4.0, 16.0),
                (15.0, 5.0),
                (19.0, 9.0),
                (8.0, 20.0),
                (4.0, 20.0),
            ]),
            Primitive::Polyline(&[
                (15.0, 5.0),
                (19.0, 9.0),
            ]),
        ],
        Icon::Error => &[
            Primitive::Circle { x: 12.0, y: 12.0, radius: 9.0 },
            Primitive::Polyline(&[
                (8.5, 8.5),
                (15.5, 15.5),
            ]),
            Primitive::Polyline(&[
                (15.5, 8.5),
                (8.5, 15.5),
            ]),
        ],
        Icon::ExternalLink => &[
            Primitive::Polyline(&[
                (14.0, 5.0),
                (19.0, 5.0),
                (19.0, 10.0),
            ]),
            Primitive::Polyline(&[
                (10.0, 14.0),
                (19.0, 5.0),
            ]),
            Primitive::Polyline(&[
                (19.0, 13.0),
                (19.0, 19.0),
                (5.0, 19.0),
                (5.0, 5.0),
                (11.0, 5.0),
            ]),
        ],
        Icon::HostKeyVerification => &[
            Primitive::Polyline(&[
                (12.0, 3.0),
                (5.0, 6.0),
                (5.0, 11.0),
                (5.1326, 12.7053),
                (5.5172, 14.2922),
                (6.1338, 15.7549),
                (6.9625, 17.0875),
                (7.9834, 18.2842),
                (9.1766, 19.3391),
                (10.5221, 20.2463),
                (12.0, 21.0),
                (13.4779, 20.2463),
                (14.8234, 19.3391),
                (16.0166, 18.2842),
                (17.0375, 17.0875),
                (17.8662, 15.7549),
                (18.4828, 14.2922),
                (18.8674, 12.7053),
                (19.0, 11.0),
                (19.0, 6.0),
                (12.0, 3.0),
            ]),
            Primitive::Circle { x: 10.0, y: 11.0, radius: 2.0 },
            Primitive::Polyline(&[
                (12.0, 11.0),
                (16.0, 11.0),
            ]),
            Primitive::Polyline(&[
                (15.0, 11.0),
                (15.0, 13.0),
            ]),
        ],
        Icon::KeyboardShortcuts => &[
            Primitive::Rectangle { x: 2.5, y: 5.0, width: 19.0, height: 14.0, radius: 2.0 },
            Primitive::FilledCircle { x: 6.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 10.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 14.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 18.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 6.005, y: 13.0, radius: 0.875 },
            Primitive::FilledCircle { x: 10.005, y: 13.0, radius: 0.875 },
            Primitive::FilledCircle { x: 14.005, y: 13.0, radius: 0.875 },
            Primitive::FilledCircle { x: 18.005, y: 13.0, radius: 0.875 },
            Primitive::Polyline(&[
                (8.0, 16.0),
                (16.0, 16.0),
            ]),
        ],
        Icon::LocalTerminal => &[
            Primitive::Rectangle { x: 3.0, y: 4.0, width: 18.0, height: 16.0, radius: 2.0 },
            Primitive::Polyline(&[
                (7.0, 9.0),
                (10.0, 12.0),
                (7.0, 15.0),
            ]),
            Primitive::Polyline(&[
                (12.5, 15.0),
                (17.0, 15.0),
            ]),
        ],
        Icon::MarkdownDocument => &[
            Primitive::Polyline(&[
                (7.0, 3.0),
                (14.0, 3.0),
                (19.0, 8.0),
                (19.0, 21.0),
                (7.0, 21.0),
                (7.0, 3.0),
            ]),
            Primitive::Polyline(&[
                (14.0, 3.0),
                (14.0, 8.0),
                (19.0, 8.0),
            ]),
            Primitive::Polyline(&[
                (10.0, 12.0),
                (16.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (10.0, 16.0),
                (16.0, 16.0),
            ]),
        ],
        Icon::Maximize => &[
            Primitive::Rectangle { x: 5.0, y: 5.0, width: 14.0, height: 14.0, radius: 1.0 },
        ],
        Icon::Minimize => &[
            Primitive::Polyline(&[
                (5.0, 17.0),
                (19.0, 17.0),
            ]),
        ],
        Icon::NewSession => &[
            Primitive::Rectangle { x: 3.0, y: 5.0, width: 14.0, height: 14.0, radius: 2.0 },
            Primitive::Polyline(&[
                (6.5, 9.0),
                (9.0, 11.5),
                (6.5, 14.0),
            ]),
            Primitive::Polyline(&[
                (10.5, 14.0),
                (13.0, 14.0),
            ]),
            Primitive::Polyline(&[
                (19.0, 8.0),
                (19.0, 14.0),
            ]),
            Primitive::Polyline(&[
                (16.0, 11.0),
                (22.0, 11.0),
            ]),
        ],
        Icon::Outline => &[
            Primitive::Circle { x: 6.0, y: 7.0, radius: 1.0 },
            Primitive::Circle { x: 6.0, y: 12.0, radius: 1.0 },
            Primitive::Circle { x: 6.0, y: 17.0, radius: 1.0 },
            Primitive::Polyline(&[
                (10.0, 7.0),
                (18.0, 7.0),
            ]),
            Primitive::Polyline(&[
                (10.0, 12.0),
                (16.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (10.0, 17.0),
                (14.0, 17.0),
            ]),
        ],
        Icon::Overflow => &[
            Primitive::FilledCircle { x: 6.0, y: 12.0, radius: 1.25 },
            Primitive::FilledCircle { x: 12.0, y: 12.0, radius: 1.25 },
            Primitive::FilledCircle { x: 18.0, y: 12.0, radius: 1.25 },
        ],
        Icon::Paste => &[
            Primitive::Polyline(&[
                (9.0, 5.0),
                (6.0, 5.0),
                (5.2346, 5.1522),
                (4.5858, 5.5858),
                (4.1522, 6.2346),
                (4.0, 7.0),
                (4.0, 19.0),
                (4.1522, 19.7654),
                (4.5858, 20.4142),
                (5.2346, 20.8478),
                (6.0, 21.0),
                (18.0, 21.0),
                (18.7654, 20.8478),
                (19.4142, 20.4142),
                (19.8478, 19.7654),
                (20.0, 19.0),
                (20.0, 7.0),
                (19.8478, 6.2346),
                (19.4142, 5.5858),
                (18.7654, 5.1522),
                (18.0, 5.0),
                (15.0, 5.0),
            ]),
            Primitive::Rectangle { x: 9.0, y: 3.0, width: 6.0, height: 4.0, radius: 1.0 },
            Primitive::Polyline(&[
                (8.0, 12.0),
                (16.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (8.0, 16.0),
                (14.0, 16.0),
            ]),
        ],
        Icon::Profile => &[
            Primitive::Rectangle { x: 3.0, y: 4.0, width: 18.0, height: 16.0, radius: 2.0 },
            Primitive::Polyline(&[
                (7.0, 9.0),
                (9.5, 11.5),
                (7.0, 14.0),
            ]),
            Primitive::Polyline(&[
                (11.0, 14.0),
                (15.0, 14.0),
            ]),
            Primitive::Polyline(&[
                (17.0, 8.0),
                (17.0, 16.0),
            ]),
        ],
        Icon::Reconnect => &[
            Primitive::Polyline(&[
                (20.0, 7.0),
                (20.0, 12.0),
                (15.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (4.0, 17.0),
                (4.0, 12.0),
                (9.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (6.1, 8.5),
                (7.3971, 6.2962),
                (9.3992, 4.7053),
                (11.8391, 3.9397),
                (14.3911, 4.1014),
                (16.7148, 5.169),
                (18.5, 7.0),
                (20.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (4.0, 12.0),
                (5.5, 17.0),
                (7.2852, 18.831),
                (9.6089, 19.8986),
                (12.1609, 20.0603),
                (14.6008, 19.2947),
                (16.6029, 17.7038),
                (17.9, 15.5),
            ]),
        ],
        Icon::RenderedView => &[
            Primitive::Polyline(&[
                (3.0, 12.0),
                (7.0, 8.5),
                (12.0, 7.0),
                (17.0, 8.5),
                (21.0, 12.0),
                (17.0, 15.5),
                (12.0, 17.0),
                (7.0, 15.5),
                (3.0, 12.0),
            ]),
            Primitive::Circle { x: 12.0, y: 12.0, radius: 2.5 },
        ],
        Icon::Restore => &[
            Primitive::Polyline(&[
                (8.0, 8.0),
                (8.0, 5.0),
                (19.0, 5.0),
                (19.0, 16.0),
                (16.0, 16.0),
            ]),
            Primitive::Rectangle { x: 5.0, y: 8.0, width: 11.0, height: 11.0, radius: 1.0 },
        ],
        Icon::Search => &[
            Primitive::Circle { x: 10.5, y: 10.5, radius: 6.5 },
            Primitive::Polyline(&[
                (15.5, 15.5),
                (20.0, 20.0),
            ]),
        ],
        Icon::SecretStorage => &[
            Primitive::Rectangle { x: 4.0, y: 10.0, width: 16.0, height: 11.0, radius: 2.0 },
            Primitive::Polyline(&[
                (8.0, 10.0),
                (8.0, 7.0),
                (8.3045, 5.4693),
                (9.1716, 4.1716),
                (10.4693, 3.3045),
                (12.0, 3.0),
                (13.5307, 3.3045),
                (14.8284, 4.1716),
                (15.6955, 5.4693),
                (16.0, 7.0),
                (16.0, 10.0),
            ]),
            Primitive::Polyline(&[
                (12.0, 14.0),
                (12.0, 17.0),
            ]),
        ],
        Icon::Serial => &[
            Primitive::Polyline(&[
                (6.0, 5.0),
                (18.0, 5.0),
                (20.0, 14.0),
                (4.0, 14.0),
                (6.0, 5.0),
            ]),
            Primitive::FilledCircle { x: 8.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 12.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 16.005, y: 9.0, radius: 0.875 },
            Primitive::FilledCircle { x: 10.005, y: 12.0, radius: 0.875 },
            Primitive::FilledCircle { x: 14.005, y: 12.0, radius: 0.875 },
            Primitive::Polyline(&[
                (9.0, 14.0),
                (9.0, 16.0),
                (9.2284, 17.1481),
                (9.8787, 18.1213),
                (10.8519, 18.7716),
                (12.0, 19.0),
                (16.0, 19.0),
            ]),
        ],
        Icon::SessionInspector => &[
            Primitive::Rectangle { x: 3.0, y: 4.0, width: 18.0, height: 16.0, radius: 2.0 },
            Primitive::Polyline(&[
                (15.0, 4.0),
                (15.0, 20.0),
            ]),
            Primitive::FilledCircle { x: 18.005, y: 9.0, radius: 0.875 },
            Primitive::Polyline(&[
                (18.0, 12.0),
                (18.0, 16.0),
            ]),
            Primitive::Polyline(&[
                (6.5, 9.0),
                (11.5, 9.0),
            ]),
            Primitive::Polyline(&[
                (6.5, 13.0),
                (11.5, 13.0),
            ]),
            Primitive::Polyline(&[
                (6.5, 16.0),
                (9.5, 16.0),
            ]),
        ],
        Icon::Settings => &[
            Primitive::Polyline(&[
                (4.0, 7.0),
                (10.0, 7.0),
            ]),
            Primitive::Polyline(&[
                (14.0, 7.0),
                (20.0, 7.0),
            ]),
            Primitive::Polyline(&[
                (4.0, 12.0),
                (14.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (18.0, 12.0),
                (20.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (4.0, 17.0),
                (7.0, 17.0),
            ]),
            Primitive::Polyline(&[
                (11.0, 17.0),
                (20.0, 17.0),
            ]),
            Primitive::Circle { x: 12.0, y: 7.0, radius: 2.0 },
            Primitive::Circle { x: 16.0, y: 12.0, radius: 2.0 },
            Primitive::Circle { x: 9.0, y: 17.0, radius: 2.0 },
        ],
        Icon::SourceView => &[
            Primitive::Polyline(&[
                (9.0, 7.0),
                (5.0, 12.0),
                (9.0, 17.0),
            ]),
            Primitive::Polyline(&[
                (15.0, 7.0),
                (19.0, 12.0),
                (15.0, 17.0),
            ]),
            Primitive::Polyline(&[
                (13.0, 5.0),
                (11.0, 19.0),
            ]),
        ],
        Icon::SshRemote => &[
            Primitive::Rectangle { x: 3.0, y: 4.0, width: 12.0, height: 12.0, radius: 2.0 },
            Primitive::Polyline(&[
                (6.5, 8.0),
                (8.5, 10.0),
                (6.5, 12.0),
            ]),
            Primitive::Polyline(&[
                (10.0, 12.0),
                (12.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (8.0, 19.0),
                (17.0, 19.0),
                (18.1481, 18.7716),
                (19.1213, 18.1213),
                (19.7716, 17.1481),
                (20.0, 16.0),
                (20.0, 13.0),
            ]),
            Primitive::Polyline(&[
                (17.0, 15.0),
                (20.0, 12.0),
                (22.5, 15.0),
            ]),
        ],
        Icon::ThemeAppearance => &[
            Primitive::Circle { x: 12.0, y: 12.0, radius: 4.0 },
            Primitive::Polyline(&[
                (12.0, 2.0),
                (12.0, 4.0),
            ]),
            Primitive::Polyline(&[
                (12.0, 20.0),
                (12.0, 22.0),
            ]),
            Primitive::Polyline(&[
                (2.0, 12.0),
                (4.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (20.0, 12.0),
                (22.0, 12.0),
            ]),
            Primitive::Polyline(&[
                (4.9, 4.9),
                (6.3, 6.3),
            ]),
            Primitive::Polyline(&[
                (17.7, 17.7),
                (19.1, 19.1),
            ]),
            Primitive::Polyline(&[
                (19.1, 4.9),
                (17.7, 6.3),
            ]),
            Primitive::Polyline(&[
                (6.3, 17.7),
                (4.9, 19.1),
            ]),
        ],
        Icon::TypographyFont => &[
            Primitive::Polyline(&[
                (5.0, 19.0),
                (11.0, 5.0),
                (13.0, 5.0),
                (19.0, 19.0),
            ]),
            Primitive::Polyline(&[
                (7.2, 14.0),
                (16.8, 14.0),
            ]),
            Primitive::Polyline(&[
                (3.0, 5.0),
                (15.0, 5.0),
            ]),
        ],
        Icon::Warning => &[
            Primitive::Polyline(&[
                (10.3, 4.6),
                (2.7, 18.0),
                (2.46, 18.664),
                (2.4657, 19.3701),
                (2.7164, 20.0302),
                (3.1808, 20.562),
                (3.8011, 20.8993),
                (4.5, 21.0),
                (19.5, 21.0),
                (20.1989, 20.8993),
                (20.8192, 20.562),
                (21.2836, 20.0302),
                (21.5343, 19.3701),
                (21.54, 18.664),
                (21.3, 18.0),
                (13.7, 4.6),
                (13.2534, 4.0951),
                (12.6645, 3.7672),
                (12.0, 3.6536),
                (11.3355, 3.7672),
                (10.7466, 4.0951),
                (10.3, 4.6),
            ]),
            Primitive::Polyline(&[
                (12.0, 9.0),
                (12.0, 14.0),
            ]),
            Primitive::FilledCircle { x: 12.005, y: 17.5, radius: 0.875 },
        ],
        Icon::Workspace => &[
            Primitive::Rectangle { x: 3.0, y: 4.0, width: 8.0, height: 7.0, radius: 1.0 },
            Primitive::Rectangle { x: 13.0, y: 4.0, width: 8.0, height: 7.0, radius: 1.0 },
            Primitive::Rectangle { x: 3.0, y: 13.0, width: 18.0, height: 7.0, radius: 1.0 },
        ],
    }
}
